[package]
name = "zluda_ld"
version = "0.0.0"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[package.metadata.zluda]
linux_only = true
linux_symlinks = [
    "zluda_ld",
    "trace/zluda_ld",
    "trace_nvidia/zluda_ld",
]
